name: Add to Project Board
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  add_to_project_board:
    runs-on: ubuntu-latest

    steps:
      - name: Add To GitHub projects
        uses: actions/add-to-project@v0.5.0
        with:
           project-url: https://github.com/users/Riaankl/projects/1/views/1
           columnName: ToDo
           github-token: ${{ secrets.GH_TOKEN }}
